### ISSUE TITLE
RxJS not created by Microsoft

### ISSUE THREAD

**Issue by richarddavenport** [schneidenbach/Angular2-AspNetCore-TypeScript-Workshop#2]
Might want to update your slides.
[ReactiveX](http://reactivex.io/)
[RxJS](https://github.com/Reactive-Extensions/RxJS)

**Comment by schneidenbach** [comment]
I'm not finding where the creator of RxJS specifically is listed, only that the RxJS's project's copyright claimant and main curator is Microsoft.

**Comment by richarddavenport** [comment]
Right, I guess my point was that Reactive programming is a paradigm, not a library. However, there are plenty of libraries out there. Also, I linked to the wrong one. The one that is curated by MS will be going away, [this is the future.](https://github.com/ReactiveX/rxjs)
